### ISSUE TITLE
Implement get my profile endpoint

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-backend#10]
### Description
This issue involves implementing an API to get the profile details. The endpoint should allow clients to make a GET request to `{{baseUrl}}/api/profile/me`.

sample response body:

```
{
  "created_at": "2023-06-29T09:15:00Z",
  "updated_at": "2023-06-30T16:45:00Z",
  "primary_email": "mentor@example.com",
  "contact_email": "mentor_contact@example.com",
  "first_name": "John",
  "last_name": "Doe",
  "image_url": "https://example.com/mentor_profile_image.jpg",
  "linkedin_url": "https://www.linkedin.com/in/johndoe",
  "type": "DEFAULT",
  "uuid": "12345678-1234-5678-1234-567812345678"
}
```

### Tasks
1. Create a controller for the `/controllers/profile` endpoint in the backend (create the route profile if not created).
2. Parse and validate the request body to ensure it matches the expected format.
3. Implement appropriate error handling and response status codes for different scenarios (e.g., validation errors, database errors).
5. Write unit tests to validate the functionality and correctness of the endpoint.

API documentation: https://documenter.getpostman.com/view/27421496/2s93m1a4ac#8744a3ee-970f-489a-853d-8b23fdee8de3

ER diagram: https://drive.google.com/file/d/11KMgdNu2mSAm0Ner8UsSPQpZJS8QNqYc/view 

### Acceptance Criteria
- The profile API endpoint `/controllers/profile` is implemented and accessible via a GET request.
- The request body is properly parsed and validated for the required format.
- Appropriate error handling is implemented, providing meaningful error messages and correct response status codes.
- Unit tests are written to validate the functionality and correctness of the endpoint.

**Comment by Shrenik0321** [comment]
can i work on this ?
