### ISSUE TITLE
Implement delete my profile endpoint

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-backend#11]
**Description:**
This issue involves implementing an API to update the profile details. The endpoint should allow clients to make a DELETE request to `{{baseUrl}}/api/me/profile/{{profileId}}`.

**Tasks:**
1. Create a controller for the `/controllers/profile` endpoint in the backend (create the route profile if not created).
2. Parse and validate the request body to ensure it matches the expected format.
3. Implement appropriate error handling and response status codes for different scenarios (e.g., validation errors, database errors).
5. Write unit tests to validate the functionality and correctness of the endpoint.

API documentation: https://documenter.getpostman.com/view/27421496/2s93m1a4ac#8744a3ee-970f-489a-853d-8b23fdee8de3

ER diagram: https://drive.google.com/file/d/11KMgdNu2mSAm0Ner8UsSPQpZJS8QNqYc/view 

**Acceptance Criteria:**
- The profile API endpoint `/controllers/profile` is implemented via a DELETE request.
- The request body is properly parsed and validated for the required format.
- Appropriate error handling is implemented, providing meaningful error messages and correct response status codes.
- Unit tests are written to validate the functionality and correctness of the endpoint.

**Additional Information:**
No

**Related Dependencies or References:**
No

**Comment by Danishkar** [comment]
can i work on this ?

**Comment by anjula-sack** [comment]
@Danishkar are you still interested in this?

**Comment by Danishkar** [comment]
@anjula-sack yes
