### ISSUE TITLE
Add Swagger API documentation

### ISSUE THREAD

**Issue by dsmabulage** [sef-global/scholarx-backend#133]
**Description:**
Implement Swagger API documentation for the backend to provide a clear, interactive, and standardized way to document and test the API endpoints.

**Tasks:**
1. Install and configure Swagger dependencies.
2. Set up Swagger configuration in the project.
3. Annotate existing API endpoints with Swagger annotations.
4. Generate Swagger documentation automatically from the annotations.

**Acceptance Criteria:**
- Swagger UI is accessible from a specific endpoint (e.g., /api-swagger).
- All existing API endpoints are documented with appropriate descriptions, request parameters, and response schemas.
- Developers can interact with the API through the Swagger UI.
- Documentation is generated automatically from the code annotations.

**Additional Information:**
Add additional information 

**Related Dependencies or References:**
Add related dependencies and references relating to the implementation.

**Comment by pswarlock** [comment]
Hi @dsmabulage 
Went through your issue and in order to implement swagger we have to annotate each endpoint with quite a lengthy comment like this.

```js
/**
 * @swagger
 * /getAccessToken:
 *   get:
 *     summary: Get access token
 *     description: Retrieve an access token from the API.
 *     responses:
 *       200:
 *         description: Access token retrieved successfully.
 *         content:
 *           application/json:
 *             schema:
 *               type: object
 *               properties:
 *                 access_token:
 *                   type: string
 */
```

Depending on the parameters accepted in the endpoint, the length of this may vary. 

Is there a better way to approach this?

**Comment by dsmabulage** [comment]
I think this will be an unnecessary burden. I will close this
