### ISSUE TITLE
Update README for Database Configuration and Migration Scripts

### ISSUE THREAD

**Issue by mayura-andrew** [sef-global/scholarx-backend#143]
---
**Description:**
We need to update the current README file to include instructions for the following database migration and seeding commands:

- `"migration:generate": "npm run typeorm:db -- migration:generate"`
- `"migration:run": "npm run typeorm:db -- migration:run"`
- `"sync:db": "npm run typeorm:db schema:sync"`
- `"seed": "npm run build && node dist/src/scripts/seed-db.js"`

This update is necessary to guide new contributors on how to configure the database correctly and understand the migration process.

**Tasks:**
1. Add a section in the README for database configuration.
   - Include details on how to set up the database.
   - Provide example configuration settings.
2. Add a section for migration commands.
   - Explain the purpose of each command (`migration:generate`, `migration:run`, `sync:db`, `seed`).
   - Provide usage examples for each command.
3. Update the existing content for clarity and coherence with the new sections.

**Acceptance Criteria:**
- The README should clearly explain how to configure the database.
- The README should provide clear and concise instructions on how to use the migration and seeding commands.
- New contributors should be able to set up and configure the database, as well as run migrations and seed the database, without confusion.

**Additional Information:**
- Ensure that all explanations and examples are clear and easy to follow.
- Consider adding links to relevant documentation or additional resources for further reading.

**Related Dependencies or References:**
- TypeORM documentation

---

**Comment by ItsLasa** [comment]
hey  @mayura-andrew  i  would like to work on this issue.

**Comment by mayura-andrew** [comment]
@ItsLasa Nice go ahead 🚀
