### ISSUE TITLE
Add backend support for mentor and mentee guides

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-backend#154]
**Description:**
Implement backend functionality to manage guide content and track user acknowledgments.

**Tasks:**
Implement database schema and API endpoints

**Acceptance Criteria:**
- [ ] Design and implement a database schema to store guide content
- [ ] Create API endpoints to serve guide content to the frontend

**Additional Information:**

**Related Dependencies or References:**
Frontend issue: [https://github.com/sef-global/scholarx-frontend/issues/164](https://github.com/sef-global/scholarx-frontend/issues/164)

**Comment by anjula-sack** [comment]
This is not required @Madhawa97
