### ISSUE TITLE
Update the public mentors API

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-backend#174]
**Description:**
The /mentors API should return the following,

1. Number of applications they recieved
2. Number of available slots

<img width="691" alt="image" src="https://github.com/user-attachments/assets/8e46df22-5947-49f2-83ed-ffe285a1128e">

**Tasks:**
- Update the API to return the following data

**Comment by anjula-sack** [comment]
@Disura-Randunu Can you work on this?

**Comment by Disura-Randunu** [comment]
> @Disura-Randunu Can you work on this?

@anjula-sack sure. Will start on this

**Comment by Disura-Randunu** [comment]
@anjula-sack "applications they recieved" means they just applied and not yet approved right?

**Comment by anjula-sack** [comment]
> @anjula-sack "applications they recieved" means mentees who just applied and not yet approved right?

All the applications mentor received. Doesn't matter the state.
