### ISSUE TITLE
Implement Get all mentors endpoint (Admin)

### ISSUE THREAD

**Issue by janithlahirukariyawasam** [sef-global/scholarx-backend#24]
**Description:**
This issue involves implementing an API to get all mentors. The endpoint should allow Admin to make a GET request to `{{baseUrl}}/api/admin/mentors?status={{status}}`.

```
[
    {
        "mentor_id": 1,
        "created_at": "2023-06-30T10:00:00Z",
        "updated_at": "2023-06-30T14:30:00Z",
        "state": "APPROVED",
        "category": "Technology",
        "application": {
            "designation": "UI/UX Designer",
            "country": "",
            "areas_of_expertise": "",
            "expectations_from_mentees": "",
            "mentoring_philosophy": "",
            "commitment_to_program": false,
            "previous_experience_as_mentor": false,
            "reason_for_being_mentor": "",
            "cv_link": ""
        },
        "availability": true,
        "profile": {
            "created_at": "2023-06-29T09:15:00Z",
            "updated_at": "2023-06-30T16:45:00Z",
            "primary_email": "mentor@example.com",
            "contact_email": "mentor_contact@example.com",
            "first_name": "John",
            "last_name": "Doe",
            "image_url": "https://example.com/mentor_profile_image.jpg",
            "linkedin_url": "https://www.linkedin.com/in/johndoe",
            "type": "DEFAULT",
            "uuid": "12345678-1234-5678-1234-567812345678"
        }
    },
    {
        "mentor_id": 2,
        "created_at": "2023-06-25T14:00:00Z",
        "updated_at": "2023-06-29T12:30:00Z",
        "state": "APPROVED",
        "category": "Business",
        "application": {
            "country": "",
            "areas_of_expertise": "",
            "expectations_from_mentees": "",
            "mentoring_philosophy": "",
            "commitment_to_program": false,
            "previous_experience_as_mentor": false,
            "reason_for_being_mentor": "",
            "cv_link": ""
        },
        "availability": false,
        "profile": {
            "created_at": "2023-06-24T08:45:00Z",
            "updated_at": "2023-06-29T16:15:00Z",
            "primary_email": "mentor2@example.com",
            "contact_email": "mentor2_contact@example.com",
            "first_name": "Jane",
            "last_name": "Smith",
            "image_url": "https://example.com/mentor2_profile_image.jpg",
            "linkedin_url": "https://www.linkedin.com/in/janesmith",
            "type": "DEFAULT",
            "uuid": "87654321-4321-8765-4321-876543218765"
        }
    }
]
```

**Tasks:**
1. Create a controller for the `/controllers/mentor` endpoint in the backend (create the route mentor if not created).
2. Parse and validate the request body to ensure it matches the expected format.
3. Implement appropriate error handling and response status codes for different scenarios (e.g., validation errors, database errors).
5. Write unit tests to validate the functionality and correctness of the endpoint.

API documentation: https://documenter.getpostman.com/view/27421496/2s93m1a4ac#8744a3ee-970f-489a-853d-8b23fdee8de3

ER diagram: https://drive.google.com/file/d/11KMgdNu2mSAm0Ner8UsSPQpZJS8QNqYc/view 

**Acceptance Criteria:**
- The profile API endpoint `/controllers/mentor` is implemented via a GET request.
- The request body is properly parsed and validated for the required format.
- Appropriate error handling is implemented, providing meaningful error messages and correct response status codes.
- Unit tests are written to validate the functionality and correctness of the endpoint.

**Additional Information:**
No

**Related Dependencies or References:**
No

**Comment by anjula-sack** [comment]
This should return the mentor application as well

**Comment by sathudeva7** [comment]
Hi,  I’d love to work on this issue.

**Comment by anjula-sack** [comment]
> Hi, I’d love to work on this issue.

Go ahead @sathudeva7

**Comment by sathudeva7** [comment]
Hi currently I have `[{"question":"What is your country?","answers":"Singapore"},{"question":"What is your expertise?","answers":"Software Engineering"},{"question":"What is your mentoring startegy?","answers":"I will provide my insights"}] `so i planned to implement this application response using switch function, according to the question it will add the value to a particular key, do you have any other idea top implement this

**Comment by sathudeva7** [comment]
```
  function switchQuestion(item: any, format: MentorInfo): void {
    switch (item[1].question.toLowerCase()) {
      case 'what is your country?':
        // Handle country-related logic
        format.country = item[1].answers
        break
      case 'what is your expertise?':
        // Handle expertise-related logic
        format.areas_of_expertise = item[1].answers
        break
      case 'what is your mentoring startegy?':
        // Handle mentoring strategy-related logic
        format.mentoring_philosophy = item[1].answers
        break
      default:
        // Handle other cases if needed
        break
    }
  }
```

**Comment by anjula-sack** [comment]
> ```
>   function switchQuestion(item: any, format: MentorInfo): void {
>     switch (item[1].question.toLowerCase()) {
>       case 'what is your country?':
>         // Handle country-related logic
>         format.country = item[1].answers
>         break
>       case 'what is your expertise?':
>         // Handle expertise-related logic
>         format.areas_of_expertise = item[1].answers
>         break
>       case 'what is your mentoring startegy?':
>         // Handle mentoring strategy-related logic
>         format.mentoring_philosophy = item[1].answers
>         break
>       default:
>         // Handle other cases if needed
>         break
>     }
>   }
> ```

Hi @sathudeva7, WIth this all you have to create an endpoint that checks the user type as admin, if so return all the mentors from the mentors table. That's pretty much it. But we have set the application to select false in the entity so you need to query that as well. 


something like this,

```
const mentor: Mentor = await mentorRepository(Mentor).findAll({
   select: ['application']
});
```

**Comment by sathudeva7** [comment]
yes, but application json looks like this in db `[{"question":"What is your country?","answers":"Singapore"},{"question":"What is your expertise?","answers":"Software Engineering"},{"question":"What is your mentoring startegy?","answers":"I will provide my insights"}]` when i get from db it return like this way so dont we need to convert according to this ```
"application": {
            "country": "",
            "areas_of_expertise": "",
            "expectations_from_mentees": "",
            "mentoring_philosophy": "",
            "commitment_to_program": false,
            "previous_experience_as_mentor": false,
            "reason_for_being_mentor": "",
            "cv_link": ""
        },
```

**Comment by anjula-sack** [comment]
> yes, but application json looks like this in db `[{"question":"What is your country?","answers":"Singapore"},{"question":"What is your expertise?","answers":"Software Engineering"},{"question":"What is your mentoring startegy?","answers":"I will provide my insights"}]` when i get from db it return like this way so dont we need to convert according to this ``` "application": { "country": "", "areas_of_expertise": "", "expectations_from_mentees": "", "mentoring_philosophy": "", "commitment_to_program": false, "previous_experience_as_mentor": false, "reason_for_being_mentor": "", "cv_link": "" },

We are building a generic type to save the application. That's why we are using a JSON type in the db level. This is out of the scope of this issue.

**Comment by sathudeva7** [comment]
![Screenshot 2023-10-04 at 12 46 32](https://github.com/sef-global/scholarx-backend/assets/67930416/9021b7f7-859b-44e1-a8b7-5e420621f052)
currenlty i have developed the api according to this sample response, so do i need to change the application field according to db

**Comment by anjula-sack** [comment]
> ![Screenshot 2023-10-04 at 12 46 32](https://user-images.githubusercontent.com/67930416/272492337-9021b7f7-859b-44e1-a8b7-5e420621f052.png) currenlty i have developed the api according to this sample response, so do i need to change the application field according to db

No looks good. Just return them called mentors instead of mentorArray. You need to write tests as well. This is a protected API only admin can access it.
