### ISSUE TITLE
Implement Get program journal(s) endpoint (Admin)

### ISSUE THREAD

**Issue by janithlahirukariyawasam** [sef-global/scholarx-backend#30]
**Description:**
This issue involves implementing an API to get program journal(s). The endpoint should allow Admin to make a GET request to `/api/admin/mentees/{{menteeId}}/journal`.

```
{
    "journal": "www.medium-blog-number-1.com"
}
```

**Tasks:**
1. Create a controller for the `/controllers/mentee` endpoint in the backend (create the route mentee if not created).
2. Parse and validate the request body to ensure it matches the expected format.
3. Implement appropriate error handling and response status codes for different scenarios (e.g., validation errors, database errors).
5. Write unit tests to validate the functionality and correctness of the endpoint.

API documentation: https://documenter.getpostman.com/view/27421496/2s93m1a4ac#8744a3ee-970f-489a-853d-8b23fdee8de3

ER diagram: https://drive.google.com/file/d/11KMgdNu2mSAm0Ner8UsSPQpZJS8QNqYc/view 

**Acceptance Criteria:**
- The profile API endpoint `/controllers/mentee` is implemented via a GET request.
- The request body is properly parsed and validated for the required format.
- Appropriate error handling is implemented, providing meaningful error messages and correct response status codes.
- Unit tests are written to validate the functionality and correctness of the endpoint.

**Additional Information:**
No

**Related Dependencies or References:**
No

**Comment by dsmabulage** [comment]
@janithlahirukariyawasam, can you please explain this journal use case? I went through the ER and the API doc but couldn't find the use case.

**Comment by dsmabulage** [comment]
> @janithlahirukariyawasam, can you please explain this journal use case? I went through the ER and the API doc but couldn't find the use case.

@anjula-sack fyi

**Comment by anjula-sack** [comment]
This requirement has changed
