### ISSUE TITLE
Implement Get all admins/users endpoint (Admins)

### ISSUE THREAD

**Issue by janithlahirukariyawasam** [sef-global/scholarx-backend#34]
**Description:**
This issue involves implementing an API to Get all admins & users. The endpoint should allow Admin to make a GET request to `{{baseUrl}}/api/admin/users`.

```
{
    "profiles": [
        {
            "created_at": "2023-06-29T09:15:00Z",
            "updated_at": "2023-06-30T16:45:00Z",
            "primary_email": "mentor@example.com",
            "contact_email": "mentor_contact@example.com",
            "first_name": "John",
            "last_name": "Doe",
            "image_url": "https://example.com/mentor_profile_image.jpg",
            "linkedin_url": "https://www.linkedin.com/in/johndoe",
            "type": "ADMIN",
            "uuid": "12345678-1234-5678-1234-567812345678"
        },
        {
            "created_at": "2023-06-29T09:45:00Z",
            "updated_at": "2023-06-30T14:15:00Z",
            "primary_email": "mentee@example.com",
            "contact_email": "mentee_contact@example.com",
            "first_name": "Sarah",
            "last_name": "Johnson",
            "image_url": "https://example.com/mentee_profile_image.jpg",
            "linkedin_url": "https://www.linkedin.com/in/sarahjohnson",
            "type": "ADMIN",
            "uuid": "98765432-2345-6789-2345-678923456789"
        },
        {
            "created_at": "2023-06-24T08:45:00Z",
            "updated_at": "2023-06-29T16:15:00Z",
            "primary_email": "mentor2@example.com",
            "contact_email": "mentor2_contact@example.com",
            "first_name": "Jane",
            "last_name": "Smith",
            "image_url": "https://example.com/mentor2_profile_image.jpg",
            "linkedin_url": "https://www.linkedin.com/in/janesmith",
            "type": "DEFAULT",
            "uuid": "87654321-4321-8765-4321-876543218765"
        },
        {
            "created_at": "2023-06-24T09:15:00Z",
            "updated_at": "2023-06-29T13:45:00Z",
            "primary_email": "mentee2@example.com",
            "contact_email": "mentee2_contact@example.com",
            "first_name": "Michael",
            "last_name": "Smith",
            "image_url": "https://example.com/mentee2_profile_image.jpg",
            "linkedin_url": "https://www.linkedin.com/in/michaelsmith",
            "type": "DEFAULT",
            "uuid": "67891234-3456-7890-3456-789034567890"
        }
    ]
}
```

**Tasks:**
1. Create a controller for the `/controllers/admin` endpoint in the backend (create the route platform if not created).
2. Parse and validate the request body to ensure it matches the expected format.
3. Implement appropriate error handling and response status codes for different scenarios (e.g., validation errors, database errors).
5. Write unit tests to validate the functionality and correctness of the endpoint.

API documentation: https://documenter.getpostman.com/view/27421496/2s93m1a4ac#8744a3ee-970f-489a-853d-8b23fdee8de3

ER diagram: https://drive.google.com/file/d/11KMgdNu2mSAm0Ner8UsSPQpZJS8QNqYc/view 

**Acceptance Criteria:**
- The profile API endpoint `/controllers/admin` is implemented via a GET request.
- The request body is properly parsed and validated for the required format.
- Appropriate error handling is implemented, providing meaningful error messages and correct response status codes.
- Unit tests are written to validate the functionality and correctness of the endpoint.

**Additional Information:**
No

**Related Dependencies or References:**
No

**Comment by Shrenik0321** [comment]
can i  work on this?

**Comment by janithlahirukariyawasam** [comment]
> can i work on this?

Sure
