### ISSUE TITLE
Implement Get all mentee emails endpoint (Admin)

### ISSUE THREAD

**Issue by janithlahirukariyawasam** [sef-global/scholarx-backend#44]
**Description:**
This issue involves implementing an API to Get all mentee emails. The endpoint should allow Admin to make a GET request to `{{baseUrl}}/api/admin/mentee/emails?status=ACCEPTED`.

```
{
    "emails": [
        "mentee@gmail.com",
        "anotherMentee@gmail.com"
    ]
}
```

**Tasks:**
1. Create a controller for the `/controllers/profile` endpoint in the backend (create the route email if not created).
2. Parse and validate the request body to ensure it matches the expected format.
3. Implement appropriate error handling and response status codes for different scenarios (e.g., validation errors, database errors).
5. Write unit tests to validate the functionality and correctness of the endpoint.

API documentation: https://documenter.getpostman.com/view/27421496/2s93m1a4ac#8744a3ee-970f-489a-853d-8b23fdee8de3

ER diagram: https://drive.google.com/file/d/11KMgdNu2mSAm0Ner8UsSPQpZJS8QNqYc/view 

**Acceptance Criteria:**
- The profile API endpoint `/controllers/profile` is implemented via a GET request.
- The request body is properly parsed and validated for the required format.
- Appropriate error handling is implemented, providing meaningful error messages and correct response status codes.
- Unit tests are written to validate the functionality and correctness of the endpoint.

**Additional Information:**
No

**Related Dependencies or References:**
No

**Comment by gautam-bhagat** [comment]
Hey , Leave this to me

**Comment by anjula-sack** [comment]
> Hey , Leave this to me

Go ahead @gautam-bhagat

**Comment by gautam-bhagat** [comment]
Hey,

I'm having issue with my nodejs in my system. It might take time. If you want you can assign this to other person!!

**Comment by janithlahirukariyawasam** [comment]
@anjula-sack  I like to work on this issue
