### ISSUE TITLE
Implement Basic Authentication with Passport.js and JWT

### ISSUE THREAD

**Issue by anjula-sack** [sef-global/scholarx-backend#6]
**Description:**
As part of our application's authentication system, we need to implement basic authentication using Passport.js and JWT (JSON Web Tokens). This will allow us to securely authenticate users and manage their sessions using JWT tokens.

**Tasks:**
1. Set up Passport.js and JWT dependencies in the project.
2. Configure Passport.js with the JWT strategy to handle authentication.
3. Implement user registration endpoint to create new user accounts securely.
4. Create a login endpoint that authenticates users and generates JWT tokens.
5. Implement a protected endpoint that requires JWT token for access.
6. Set up middleware to authenticate requests using Passport.js and the JWT strategy.
7. Handle logout functionality to invalidate tokens or sessions.
8. Implement password reset functionality for users who have forgotten their password.

**Acceptance Criteria:**
- Users should be able to register and create new accounts securely.
- Users should be able to log in and receive a JWT token for subsequent authenticated requests.
- The protected endpoint should only be accessible with a valid JWT token.
- JWT tokens should be properly validated, and expired or invalid tokens should be rejected.
- Users should be able to log out and invalidate their session or token.
- The password reset functionality should allow users to reset their password securely.

**Additional Information:**
- Make sure to follow best practices for security, such as properly hashing passwords and securely handling JWT tokens.
- Document the authentication API endpoints and any required input parameters or response formats.
- Ensure that appropriate error handling is implemented for various scenarios, such as invalid credentials or expired tokens.

**Related Dependencies or References:**
- Passport.js: [link to documentation](https://www.passportjs.org/)
- JWT: [link to documentation](https://jwt.io/)

**Comment by sathsarabandaraj** [comment]
Shall I work on this
