### ISSUE TITLE
Add instructions for generating the JWT_SECRET

### ISSUE THREAD

**Issue by Piumal1999** [sef-global/scholarx-backend#62]
**Description:**
The README.md doesn't contain the instructions on creating the JWT_SECRET key.

**Tasks:**
Add the relevant details to the readme file. (A reference link or the instructions itself)

**Acceptance Criteria:**
N/A

**Additional Information:**
N/A

**Related Dependencies or References:**
N/A

**Comment by anjula-sack** [comment]
Closing this since it's not required
