### ISSUE TITLE
Update README with Google Authentication Setup Instructions

### ISSUE THREAD

**Issue by mayura-andrew** [sef-global/scholarx-backend#94]
**Title:** 
Update README with Google Authentication Setup Instructions

**Description:**
The README currently lacks instructions on how to set up Google Authentication. This can be confusing for new contributors who are trying to run the project locally. We need to add clear and concise instructions on how to set up Google Authentication.

**Tasks:**

1. Add a new section in the README titled "Setting up Google Authentication".
2. Explain how to create a new project in the Google Cloud Console.
3. Explain how to enable the Google+ API for the project.
4. Explain how to create OAuth client ID credentials.
5. Explain how to set the GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, and GOOGLE_REDIRECT_URL environment variables.
6. Include screenshots where necessary to make the instructions clearer.

**Acceptance Criteria:**

The README should have clear instructions on how to set up Google Authentication.
A new contributor should be able to follow the instructions to set up Google Authentication and run the project locally.
Additional Information: None.

**Related Dependencies or References:**

Google Cloud Console: https://console.cloud.google.com/
OAuth 2.0: https://developers.google.com/identity/protocols/oauth2

**Comment by vishwaikon** [comment]
@mayura-andrew I made the changes in the README file, Please mention if there's anything to be improved . Regards!
![Screen Recording (1-23-2024 5-21-55 PM)](https://github.com/sef-global/scholarx-backend/assets/75526380/c9d48919-9883-4ce8-8063-6a609a872f0d)

**Comment by mayura-andrew** [comment]
@vishwaikon superb :) can you open a pr for this?

**Comment by vishwaikon** [comment]
@mayura-andrew  Sure, I'll.

**Comment by mayura-andrew** [comment]
did you join our Slack channel?

**Comment by vishwaikon** [comment]
Yeah , I joined.
