### ISSUE TITLE
Implement apply for a mentor endpoint (Mentee)

### ISSUE THREAD

**Issue by Madhawa97** [sef-global/scholarx-backend#99]
**Description:**
This issue involves implementing the Mentee API endpoint. The endpoint should allow clients to make a POST request to `{{baseUrl}}/api/mentees` and provide related information in the request body. 

```json
{
    "mentor_id": "280a5eb6-323d-47b1-92da-b7a1e7fbc32c",
    "application": [
        {
            "question": "What is your university?",
            "answers": "University of Colombo"
        },
        {
            "question": "What are your interests?",
            "answers": "Software Engineering"
        },
        ...
    ]
}
```  

**Tasks:**
1. Create a route and controller for the `/controllers/mentees` endpoint in the Node.js backend.
2. Parse and validate the request body to ensure it matches the expected format.
3. Store the mentee information in the database.
4. Implement appropriate error handling and response status codes for different scenarios (e.g., validation errors, database errors).
5. Write unit tests to validate the functionality and correctness of the endpoint.

API documentation: [Postman Collection](https://documenter.getpostman.com/view/27421496/2s93m1a4ac#e4051292-0028-4564-95aa-c4042fd0b6fb)

ER diagram: [Google Drive](https://drive.google.com/file/d/11KMgdNu2mSAm0Ner8UsSPQpZJS8QNqYc/view)

**Acceptance Criteria:**
1. The Mentor API endpoint `/controllers/mentees` is implemented and accessible via a POST request.
2. The request body is properly parsed and validated for the required format.
3. The mentor information, including the questions and answers, is stored correctly in the database.
4. Appropriate error handling is implemented, providing meaningful error messages and correct response status codes.
5. Unit tests are written to validate the functionality and correctness of the endpoint.

**Comment by ifhammohamed1111** [comment]
Hi @Madhawa97 , @mayura-andrew !

shall i work on this issue.

**Comment by Madhawa97** [comment]
Yes. Go ahead @ifhammohamed1111 

cc:  @anjula-sack

**Comment by anjula-sack** [comment]
Sorry @ifhammohamed1111 This is implemented by this https://github.com/sef-global/scholarx-backend/pull/107. Will you be able to work on something else?

**Comment by ifhammohamed1111** [comment]
yeah no issues @anjula-sack !
